### ISSUE TITLE
Morning-session-discussion 

### ISSUE THREAD

**Issue by mahdimahdawi** [ZikaZaki/zikazaki-folio#11]

**Comment by ZikaZaki** [comment]
Thank you **Mahdi** for opening this issue so we can discuss the code review process.
So first thing is first, how did you find my code guys?

**Comment by tarikbouari** [comment]
I think you use a good semantic tag in Html

**Comment by mahdimahdawi** [comment]
please kindly add placeholder attribute in textarea field.

**Comment by ZikaZaki** [comment]
Thanks you guys for your time reviewing my code.

**Comment by ZikaZaki** [comment]
> please kindly add placeholder attribute in textarea field.

I already did brother **Mahdi**. Thanks for your time.
